### ISSUE TITLE
Can You Merge with CrossPlatform libraries

### ISSUE THREAD

**Issue by rohitsangwan01** [woodemi/web_blue.dart#1]
Hey , can you try to merge this with flutter reactive_ble or your quick_blue after updating that to null safe, it would be great to have a single package for true cross platform devlopment

**Comment by Sunbreak** [comment]
I dont think so. Too different APIs

**Comment by rohitsangwan01** [comment]
@Sunbreak  okk , can you add a sample flutter web app link live hosted somewhere with this library in readme

**Comment by Sunbreak** [comment]
There is an example. It works

**Comment by rohitsangwan01** [comment]
@Sunbreak 
 yeah just tried that , its working, i was asking for a web link in readme , so that other peoples can click on it and see the functionality without setting up on their own machine , anyway its up to you

**Comment by Sunbreak** [comment]
Thx. I'd like to setup a live example until I merge [web_blue.dart](https://github.com/woodemi/web_blue.dart), [web_usb.dart](https://github.com/woodemi/web_usb.dart) and [web_hid.dart](https://github.com/woodemi/web_hid.dart)
